version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DB:-trading}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro

  sentiment:
    build: ./sentiment_service
    environment:
      - UVICORN_PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  worker:
    build: ./workers
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      sentiment:
        condition: service_healthy
    restart: unless-stopped

volumes:
  dbdata:
